before_install:
- sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng latex-xcolor
  texlive-full
script:
- chmod +x build.sh
- "./build.sh"
deploy:
  provider: releases
  api_key:
    secure: nrHVC1w0a7MJsYPK7C1dWOCGMPZ5ZsJ0Ek7A+L8gD3UHRynMfTCqt2sC68JNH5Wjymx8mce2aSi9Sn7TfEnzbZSQ2lyjA0DwHj0sxSLYqAXpzFh+vFNL0sEa4CdtfyW3yeqhefdpKXD3YTtJs+l84BW2PU2Jxn0wGm0xgZgZHD1cFUw7rCgWbHb/P7nbgqB+M6QeSN0FoMvnxLJyxaSXEkjhPJdAFj1kq1SnsgW5hZiGjNqfLpulIIcbeBHrIR+bQvseV7f9hPxtfyhAUWCtEEd96FXyR03eVWStWK2J1tDYV7c3XVhtNGbbMq4VMj391OTVWURIXmSuSRPEsfaRynrSHzYABHoloOJjOfPL0ibNXtfY+0+tXd3XezyYe5ScmO0JbvZTX1O+F3/aldVY767flIBW2NC+7q3HnpTuwyzRYAYlXCsarlS80o5qV0tuIKEAO+C5/MiqWs8qtdsOyzCXM7rghbk8XnFc4EwLdusld2zW5WFmbpzumtkeOVfQMaH2Oji8K+vcqpCPL9DsowurzhkD3lmYLXmRq7ob+du5KGsBDI4WQnIJgnoDZifb4uHZRaBL3fj+l/cPVF8miBua9d+U35g8rb44+XXSZxzR6T8YLjo/2UgOIr1Y7FDDZ0b1X7iZopda1mkynOfHMeliNZV8bHZ+JPA98jzQ2po=
  file: "./_build/manual.pdf"
  skip_cleanup: true
  on:
    repo: caccs/Manual-do-Bixo
    tags: true
