before_install:
- sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng latex-xcolor
  texlive-full

script:
- chmod +x build.sh
- ./build.sh
deploy:
  provider: releases
  api_key:
    secure: l/Co62r8zQdFrCczRK4U9JhyAO0kk20p34iwlk+zfJyfKeCcky05RCso0g5P6jEDL3wXmXl2au/qh22h1iYmoUxgvg/BjDUkpu+lFG//Xd+DFUl0YDK6WjKBWqGIhL/FaOhqRH0pDcfH8R3dKatFvY2XThJNCHAomQh8bs1hgyAlIpjux03lcLeymLBC2N/SYWFKysZFv/3P2VnRMjeoPU0Yc7R2+DeM3vOtdkHTw5Y05wMbttTz1mff2tC43eMiHIHV8R0aAjWLvVo+arClQqP7T/Qd2vQ+lMBwerBUVTm9NNszum33nStWRid7E75s2RWmNomX979g4qR0hS0TKgO+Qvyr6dzAHMVT8TZ53uQD7IPhw+cKhwhlDgvxWvaqFE3mHNlOoc3kja3qqMh1Il7/kCnyy0Rj2DjK35kklZIEt74J9pXo7ukuIlPBvsWXCl2L/daKRvsHUCJ86z+crAeWc8AGkmbonHw3razVlbagb7FGTVx8zmLG5nuKFtmqoAsq7fpQIr+tpsVcrnkvKYFVLphM3i0XdzXmFWPocPwIPuJNSR0GMrr+0tJ8bSZW17DhLFGZCWniM68OqSYjCmpLQT1Jw20C8Cao2QsycC/I0hNIE8Dl45+uKmnDbl2lZWjLoP8FCdd0CTVJjiAPJrz0yMsm+B1VYjMln5jDRzA=
  file: "./_build/manual.pdf"
  skip_cleanup: true
  on:
    tags: true
    repo: caccs/Manual-do-Bixo
